apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: app-secrets
  namespace: fitness-platform-production
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: secrets-backend
    kind: ClusterSecretStore
  target:
    name: app-secrets
    creationPolicy: Owner
  data:
    - secretKey: JWT_PRIVATE_KEY_PEM
      remoteRef:
        key: fitpulse/production/app-secrets
        property: JWT_PRIVATE_KEY_PEM
    - secretKey: JWT_PUBLIC_KEY_PEM
      remoteRef:
        key: fitpulse/production/app-secrets
        property: JWT_PUBLIC_KEY_PEM
    - secretKey: RABBITMQ_URL
      remoteRef:
        key: fitpulse/production/app-secrets
        property: RABBITMQ_URL
    - secretKey: REDIS_PASSWORD
      remoteRef:
        key: fitpulse/production/app-secrets
        property: REDIS_PASSWORD
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: fitpulse/production/app-secrets
        property: POSTGRES_PASSWORD
    - secretKey: GOOGLE_CLIENT_ID
      remoteRef:
        key: fitpulse/production/app-secrets
        property: GOOGLE_CLIENT_ID
    - secretKey: GOOGLE_CLIENT_SECRET
      remoteRef:
        key: fitpulse/production/app-secrets
        property: GOOGLE_CLIENT_SECRET
    - secretKey: SMTP_PASSWORD
      remoteRef:
        key: fitpulse/production/app-secrets
        property: SMTP_PASSWORD
    - secretKey: TOTP_ENCRYPTION_KEY
      remoteRef:
        key: fitpulse/production/app-secrets
        property: TOTP_ENCRYPTION_KEY
