apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: secrets-backend-postgresql
  namespace: external-secrets
spec:
  provider:
    postgresql:
      host: postgres-service.fitness-platform-production.svc.cluster.local
      port: 5432
      database: fitness_platform
      tls:
        mode: require
      auth:
        user:
          secretRef:
            name: external-secrets-db-credentials
            key: username
        password:
          secretRef:
            name: external-secrets-db-credentials
            key: password
      ca:
        secretRef:
          name: postgres-tls
          key: ca.crt
      parameters:
        table: external_secrets
        key_column: name
        value_column: value
        created_at_column: created_at
        updated_at_column: updated_at
