#!/usr/bin/env bash
# configs/k8s/scripts/fix-dns.sh
# ============================================================================
# Permanent DNS Fix Script for VPS
# ----------------------------------------------------------------------------
# Solves the issue when DHCP provides broken link-local DNS (e.g. 169.254.2.3)
# that causes apt/docker/git/k3s failures.
#
# What it does:
#   1. Removes immutable flag from /etc/resolv.conf (if set)
#   2. Backs up current resolv.conf
#   3. Writes working DNS resolvers (Google + Cloudflare)
#   4. Protects resolv.conf from being overwritten (chattr +i)
#   5. Configures dhclient to supersede broken DHCP DNS
#   6. Verifies DNS resolution works
#
# Usage:
#   sudo ./fix-dns.sh
#   sudo ./fix-dns.sh --verify-only     # only verify, don't modify
#   sudo ./fix-dns.sh --no-protect      # skip chattr +i (for debugging)
# ============================================================================
set -euo pipefail

# ----------------------------------------------------------------------------
# Configuration
# ----------------------------------------------------------------------------
readonly RESOLV_CONF="/etc/resolv.conf"
readonly DHCLIENT_CONF="/etc/dhcp/dhclient.conf"
readonly BACKUP_FILE="${RESOLV_CONF}.bak.$(date +%Y%m%d_%H%M%S)"

# Working DNS resolvers
readonly DNS_SERVERS=(
	"8.8.8.8"       # Google Primary
	"1.1.1.1"       # Cloudflare Primary
	"8.8.4.4"       # Google Secondary
)

# Test domains for verification
readonly TEST_DOMAINS=(
	"archive.ubuntu.com"
	"github.com"
	"registry-1.docker.io"
)

# ----------------------------------------------------------------------------
# Colors & logging
# ----------------------------------------------------------------------------
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
BOLD='\033[1m'
NC='\033[0m'

log_info()  { echo -e "${CYAN}[INFO]${NC}  $*"; }
log_ok()    { echo -e "${GREEN}[OK]${NC}    $*"; }
log_warn()  { echo -e "${YELLOW}[WARN]${NC}  $*"; }
log_error() { echo -e "${RED}[ERROR]${NC} $*" >&2; }
log_step()  { echo -e "\n${BOLD}==>${NC} ${BOLD}$*${NC}"; }

# ----------------------------------------------------------------------------
# Argument parsing
# ----------------------------------------------------------------------------
VERIFY_ONLY=false
PROTECT_FILE=true

while [[ $# -gt 0 ]]; do
	case "$1" in
		--verify-only)
			VERIFY_ONLY=true
			shift
			;;
		--no-protect)
			PROTECT_FILE=false
			shift
			;;
		-h|--help)
			echo "Usage: $0 [--verify-only] [--no-protect]"
			echo "  --verify-only   Only verify DNS works, don't modify anything"
			echo "  --no-protect    Skip chattr +i (useful for debugging)"
			exit 0
			;;
		*)
			log_error "Unknown option: $1"
			exit 1
			;;
	esac
done

# ----------------------------------------------------------------------------
# Pre-flight checks
# ----------------------------------------------------------------------------
preflight_checks() {
	log_step "Running pre-flight checks"

	if [[ $EUID -ne 0 ]]; then
		log_error "This script must be run as root (use sudo)"
		exit 1
	fi

	if [[ ! -d /etc/dhcp ]]; then
		log_warn "/etc/dhcp does not exist, creating..."
		mkdir -p /etc/dhcp
	fi

	log_ok "Pre-flight checks passed"
}

# ----------------------------------------------------------------------------
# Remove immutable flag
# ----------------------------------------------------------------------------
remove_immutable_flag() {
	log_step "Removing immutable flag from ${RESOLV_CONF}"

	if [[ -f "$RESOLV_CONF" ]]; then
		if lsattr "$RESOLV_CONF" 2>/dev/null | grep -q -- '----i'; then
			chattr -i "$RESOLV_CONF" || true
			log_ok "Immutable flag removed"
		else
			log_info "File is not immutable, skipping"
		fi
	else
		log_warn "${RESOLV_CONF} does not exist"
	fi
}

# ----------------------------------------------------------------------------
# Backup current resolv.conf
# ----------------------------------------------------------------------------
backup_resolv_conf() {
	log_step "Backing up current ${RESOLV_CONF}"

	if [[ -f "$RESOLV_CONF" ]]; then
		cp "$RESOLV_CONF" "$BACKUP_FILE"
		log_ok "Backup created: ${BACKUP_FILE}"
	else
		log_warn "No existing ${RESOLV_CONF} to backup"
	fi
}

# ----------------------------------------------------------------------------
# Write new resolv.conf
# ----------------------------------------------------------------------------
write_resolv_conf() {
	log_step "Writing new ${RESOLV_CONF}"

	cat > "$RESOLV_CONF" <<EOF
# Fixed DNS - working resolvers (managed by CI/CD)
# Generated by fix-dns.sh on $(date -u '+%Y-%m-%d %H:%M:%S UTC')
# DO NOT EDIT — file is protected with chattr +i
$(printf 'nameserver %s\n' "${DNS_SERVERS[@]}")
options timeout:2 attempts:3 rotate
EOF

	chmod 644 "$RESOLV_CONF"
	log_ok "${RESOLV_CONF} written with ${#DNS_SERVERS[@]} nameservers"
}

# ----------------------------------------------------------------------------
# Protect resolv.conf from being overwritten
# ----------------------------------------------------------------------------
protect_resolv_conf() {
	log_step "Protecting ${RESOLV_CONF} from overwrites"

	if [[ "$PROTECT_FILE" == "false" ]]; then
		log_warn "Skipping protection (--no-protect flag set)"
		return 0
	fi

	if chattr +i "$RESOLV_CONF" 2>/dev/null; then
		log_ok "File protected with immutable flag"
	else
		log_warn "Failed to set immutable flag (filesystem may not support it)"
	fi
}

# ----------------------------------------------------------------------------
# Configure dhclient to supersede broken DHCP DNS
# ----------------------------------------------------------------------------
configure_dhclient() {
	log_step "Configuring ${DHCLIENT_CONF}"

	local dns_list
	dns_list=$(IFS=', '; echo "${DNS_SERVERS[*]}")

	cat > "$DHCLIENT_CONF" <<EOF
# Override DNS settings - prevent broken DHCP DNS
# Managed by CI/CD (fix-dns.sh)
# Generated on $(date -u '+%Y-%m-%d %H:%M:%S UTC')

supersede domain-name-servers ${dns_list};

request subnet-mask, broadcast-address, time-offset, routers,
		domain-name, domain-search, host-name,
		dhcp6.name-servers, dhcp6.domain-search, dhcp6.fqdn, dhcp6.sntp-servers,
		netbios-name-servers, netbios-scope, interface-mtu,
		rfc3442-classless-static-routes, ntp-servers;
EOF

	chmod 644 "$DHCLIENT_CONF"
	log_ok "${DHCLIENT_CONF} configured"
}

# ----------------------------------------------------------------------------
# Verify DNS resolution
# ----------------------------------------------------------------------------
verify_dns() {
	log_step "Verifying DNS resolution"

	local failed=0
	local passed=0

	for domain in "${TEST_DOMAINS[@]}"; do
		if nslookup "$domain" >/dev/null 2>&1; then
			log_ok "✓ ${domain}"
			((passed++))
		else
			log_error "✗ ${domain}"
			((failed++))
		fi
	done

	echo ""
	log_info "DNS verification: ${passed} passed, ${failed} failed"

	if [[ $failed -gt 0 ]]; then
		log_error "DNS verification failed!"
		echo ""
		log_info "Current ${RESOLV_CONF}:"
		cat "$RESOLV_CONF"
		return 1
	fi

	return 0
}

# ----------------------------------------------------------------------------
# Print final status
# ----------------------------------------------------------------------------
print_final_status() {
	log_step "Final status"

	echo ""
	echo -e "${BOLD}Current ${RESOLV_CONF}:${NC}"
	echo "----------------------------------------"
	cat "$RESOLV_CONF"
	echo "----------------------------------------"
	echo ""

	if lsattr "$RESOLV_CONF" 2>/dev/null | grep -q -- '----i'; then
		log_ok "File is PROTECTED (immutable flag set)"
	else
		log_warn "File is NOT protected"
	fi

	echo ""
	log_ok "✅ DNS fix completed successfully!"
}

# ----------------------------------------------------------------------------
# Main
# ----------------------------------------------------------------------------
main() {
	echo ""
	echo -e "${BOLD}${CYAN}============================================${NC}"
	echo -e "${BOLD}${CYAN}  VPS DNS Fix Script${NC}"
	echo -e "${BOLD}${CYAN}============================================${NC}"
	echo ""
	log_info "Verify only: ${VERIFY_ONLY}"
	log_info "Protect file: ${PROTECT_FILE}"

	preflight_checks

	if [[ "$VERIFY_ONLY" == "true" ]]; then
		verify_dns
		exit $?
	fi

	remove_immutable_flag
	backup_resolv_conf
	write_resolv_conf
	protect_resolv_conf
	configure_dhclient
	verify_dns
	print_final_status
}

main "$@"
