apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - postgres.yaml
  - redis.yaml
  - rabbitmq-statefulset.yaml
  - user-service.yaml
  - biometric-service.yaml
  - training-service.yaml
  - gateway.yaml
  - device-connector.yaml
  - device-emulator.yaml
  - ml-classifier.yaml
  - ml-generator.yaml
