apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - postgres.yaml
  - postgres-config.yaml
  - redis.yaml
  - redis-config.yaml
  # - rabbitmq-statefulset.yaml   # временно отключено
  - user-service.yaml
  # - biometric-service.yaml      # временно отключено
  # - training-service.yaml       # временно отключено
  - gateway.yaml
  # - device-connector.yaml       # временно отключено
  # - classifier.yaml             # временно отключено
  # - ml-generator.yaml           # временно отключено
