apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-classifier
spec:
  revisionHistoryLimit: 1
  replicas: 1
  selector:
    matchLabels:
      app: ml-classifier
  template:
    metadata:
      labels:
        app: ml-classifier
        zone: app-zone
    spec:
      securityContext:
        runAsUser: 1001
      imagePullSecrets:
      - name: ghcr-pull-secret
      serviceAccountName: app-service-account
      volumes:
      - name: tmp
        emptyDir: {}
      - name: models          
        emptyDir: {}
      containers:
      - name: ml-classifier
        image: ghcr.io/mamuer/project/ml-classifier:latest
        imagePullPolicy: IfNotPresent
        securityContext:
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
        ports:
        - containerPort: 8001
          name: http
        volumeMounts:
        - name: tmp
          mountPath: /tmp
        env:
        - name: ML_CLASSIFIER_PORT
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: ML_CLASSIFIER_PORT
        - name: MPLCONFIGDIR
          value: "/tmp/matplotlib"
        livenessProbe:
          httpGet:
            path: /health
            port: 8001
          initialDelaySeconds: 180
          periodSeconds: 10
          timeoutSeconds: 10
          failureThreshold: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8001
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "500m"
