apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: fitness-platform-production
resources:
  - ../../base
  - ingress.yaml
  - gateway-nodeport.yaml
  - hpa.yaml
patches:
  - path: replica-gateway.yaml
  - path: replica-user-service.yaml
  - path: replica-biometric-service.yaml
  - path: replica-training-service.yaml
  - path: replica-device-connector.yaml
  - path: replica-classifier.yaml
  - path: replica-ml-generator.yaml
  - path: replicas-patch.yaml
  - path: resource-gateway.yaml
  - path: resource-user-service.yaml
  - path: resource-biometric-service.yaml
  - path: resource-training-service.yaml
  - path: resource-device-connector.yaml
  - path: resource-classifier.yaml
  - path: resource-ml-generator.yaml
  - path: configmap-patch.yaml
    target:
      kind: ConfigMap
      name: app-config
labels:
  - pairs:
      environment: production
images:
  - name: ghcr.io/mamuer/project/user-service
    newTag: ${IMAGE_TAG:-latest}
  - name: ghcr.io/mamuer/project/biometric-service
    newTag: ${IMAGE_TAG:-latest}
  - name: ghcr.io/mamuer/project/training-service
    newTag: ${IMAGE_TAG:-latest}
  - name: ghcr.io/mamuer/project/gateway
    newTag: ${IMAGE_TAG:-latest}
  - name: ghcr.io/mamuer/project/classifier
    newTag: ${IMAGE_TAG:-latest}
  - name: ghcr.io/mamuer/project/ml-generator
    newTag: ${IMAGE_TAG:-latest}