apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: fitness-platform-production

resources:
  - ../../base
  - ingress.yaml
  - gateway-nodeport.yaml
  - hpa.yaml
  - replica-gateway.yaml
  - replica-user-service.yaml
  - replica-biometric-service.yaml
  - replica-training-service.yaml
  - replica-device-connector.yaml
  - replica-ml-classifier.yaml
  - replica-ml-generator.yaml
  - resource-redis.yaml
  - resource-gateway.yaml
  - resource-user-service.yaml
  - resource-biometric-service.yaml
  - resource-training-service.yaml
  - resource-device-connector.yaml
  - resource-ml-classifier.yaml
  - resource-ml-generator.yaml
  - configmap-patch.yaml

labels:
  - pairs:
      environment: production

images:
  - name: ghcr.io/mamuer/project/user-service
    newTag: ${IMAGE_TAG:-latest}
  - name: ghcr.io/mamuer/project/biometric-service
    newTag: ${IMAGE_TAG:-latest}
  - name: ghcr.io/mamuer/project/training-service
    newTag: ${IMAGE_TAG:-latest}
  - name: ghcr.io/mamuer/project/gateway
    newTag: ${IMAGE_TAG:-latest}
  - name: ghcr.io/mamuer/project/ml-classifier
    newTag: ${IMAGE_TAG:-latest}
  - name: ghcr.io/mamuer/project/ml-generator
    newTag: ${IMAGE_TAG:-latest}
