apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: biometric-service
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: training-service
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: device-connector
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-classifier
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-generator
spec:
  replicas: 1