apiVersion: apps/v1
kind: Deployment
metadata:
  name: classifier
  namespace: fitness-platform-production
spec:
  template:
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
        - name: classifier
          securityContext:
            runAsNonRoot: true
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 500m
              memory: 256Mi
