apiVersion: apps/v1
kind: Deployment
metadata:
  name: device-connector
  namespace: fitness-platform-production
spec:
  template:
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
        - name: device-connector
          securityContext:
            runAsNonRoot: true
          resources:
            requests:
              cpu: 25m
              memory: 64Mi
            limits:
              cpu: 100m
              memory: 128Mi
