sonar.projectKey=fitness-platform
sonar.projectName=FitPulse Platform
sonar.organization=mamuer

sonar.sources=cmd,internal,api,web/src
sonar.tests=cmd,internal
sonar.test.inclusions=**/*_test.go,**/*.test.jsx,**/*.test.js

sonar.exclusions=api/gen/**,web/dist/**,web/node_modules/**,mocks/**,**/*_test.go,**/*.test.jsx,**/*.test.js,**/swagger.yaml,**/openapi.yaml,**/*.proto,**/*.pb.go
sonar.coverage.exclusions=api/gen/**,web/dist/**,web/node_modules/**,mocks/**,cmd/ml-classifier/**,cmd/device-emulator/**,**/swagger.yaml,**/openapi.yaml,**/*.proto,**/*.pb.go,cmd/ml_generator/main.py,web/src/components/**

sonar.go.coverage.reportPaths=coverage.out
sonar.javascript.lcov.reportPaths=web/coverage/lcov.info

sonar.qualitygate.wait=true
