sonar.projectKey=fitness-platform
sonar.projectName=FitPulse Platform
sonar.organization=mamuer

sonar.sources=cmd,internal,api,web/src
sonar.tests=cmd,internal,web/src
sonar.test.inclusions=**/*_test.go,**/*.test.jsx,**/*.test.js

sonar.exclusions=api/gen/**,web/dist/**,web/node_modules/**,mocks/**,**/*_test.go,**/*.test.jsx,**/*.test.js,**/swagger.yaml,**/openapi.yaml,**/*.proto,**/*.pb.go,configs/k8s/base/local-path-provisioner.yaml
sonar.coverage.exclusions=api/gen/**,web/dist/**,web/node_modules/**,mocks/**,cmd/ml-classifier/**,cmd/device-emulator/**,**/swagger.yaml,**/openapi.yaml,**/*.proto,**/*.pb.go,cmd/ml_generator/main.py,cmd/**/main.go,web/src/main.jsx,web/src/App.jsx,web/src/index.css,web/src/test/setup.js

sonar.go.coverage.reportPaths=coverage/coverage.out
sonar.javascript.lcov.reportPaths=coverage/lcov.info

sonar.qualitygate.wait=true

sonar.python.version=3.14
