apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: init-db-sql
    files:
      - init.sql=init-db.sql
    options:
      disableNameSuffixHash: true # <-- добавьте эту строку

resources:
  - migrate-db.yaml
  - seed-admin.yaml
