apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
  namespace: fitness-platform-production
type: Opaque
stringData:
  rabbitmq.conf: |
    default_user = $RABBITMQ_USER
    default_pass = $RABBITMQ_PASS
