apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
  namespace: fitness-platform-production
type: Opaque
stringData:
  rabbitmq.conf: |
    # Credentials are provided via RABBITMQ_DEFAULT_USER_FILE and RABBITMQ_DEFAULT_PASS_FILE
