apiVersion: v1
kind: ServiceAccount
metadata:
  name: kibana
  namespace: elk
  labels:
    app: kibana
    component: logging
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kibana
  namespace: elk
  labels:
    app: kibana
    component: logging
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "endpoints"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kibana
  namespace: elk
  labels:
    app: kibana
    component: logging
subjects:
  - kind: ServiceAccount
    name: kibana
    namespace: elk
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kibana
