import { loadState } from '../services/storage';

export const defaultState = {
  screen: 'login',
  theme: 'dark',
  highContrast: false,
  language: 'ru',
  period: 'День',
  monthOpen: false,
  selectedMeal: null,
  selectedMetric: null,
  selectedWorkout: null,
  selectedPlace: 'Дом',
  nutritionView: 'День',
  calendarMonthIndex: new Date().getMonth(),
  calendarYear: new Date().getFullYear(),
  profileImage: '',
  profile: {
    name: 'Михаил',
    gender: 'Мужской',
    email: 'mih@example.com',
    phone: '+7 999 123 45 67',
    twoFactor: false,
    backupCodesRemaining: 0,
    assistantStyle: 'Дружелюбный',
    devices: ['Apple Watch', 'Смарт-весы'],
    bio: 'Люблю спорт и здоровое питание 💪',
    status: 'Активен',
    friends: 12,
    password: '',
  },
  twoFactorSetup: null,
  twoFactorTempToken: null,
  messages: [
    {
      id: 'default-ai',
      type: 'ai',
      text: 'Привет! Я FitPulse AI. Могу помочь с питанием, тренировками, календарём и ответить на вопросы.',
    },
  ],
  events: [
    {
      type: 'training',
      title: 'Силовая база',
      info: 'Ноги, корпус и стабилизация',
      time: '18:30',
      date: '24 июля',
      color: '#6fae20',
    },
    {
      type: 'food',
      title: 'Курица с гречкой',
      info: '480 ккал · Б 38 г · Ж 14 г · У 48 г',
      time: '13:20',
      date: '24 июля',
      color: '#f5d45d',
    },
    {
      type: 'recovery',
      title: 'Восстановление',
      info: 'Дыхание и растяжка',
      time: '21:30',
      date: '25 июля',
      color: '#ff6375',
    },
  ],
  weightHistory: [
    ['01 июля', '76.1 кг'],
    ['08 июля', '75.4 кг'],
    ['15 июля', '74.8 кг'],
    ['22 июля', '74.2 кг'],
  ],
  meals: {
    breakfast: {
      label: 'Завтрак',
      icon: 'fa-sun',
      time: '08:00',
      title: 'Овсянка с ягодами',
      kcal: 360,
      macros: 'Б 16 г · Ж 10 г · У 51 г',
      image:
        'https://images.unsplash.com/photo-1490474418585-ba9bad8fd0ea?w=500',
    },
    lunch: {
      label: 'Обед',
      icon: 'fa-bowl-food',
      time: '13:20',
      title: 'Курица с гречкой',
      kcal: 480,
      macros: 'Б 38 г · Ж 14 г · У 48 г',
      image: 'https://images.unsplash.com/photo-1547592180-85f173990554?w=500',
    },
    dinner: {
      label: 'Ужин',
      icon: 'fa-moon',
      time: '19:30',
      title: 'Боул с лососем',
      kcal: 540,
      macros: 'Б 34 г · Ж 22 г · У 48 г',
      image:
        'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=500',
    },
    snack: {
      label: 'Полдник',
      icon: 'fa-apple-whole',
      time: '16:30',
      title: 'Йогурт и ягоды',
      kcal: 210,
      macros: 'Б 18 г · Ж 5 г · У 24 г',
      image:
        'https://images.unsplash.com/photo-1488477181946-6428a0291777?w=500',
    },
  },
  alternatives: {
    breakfast: [
      [
        'Омлет со шпинатом',
        390,
        'Б 27 г · Ж 21 г · У 18 г',
        'https://images.unsplash.com/photo-1525351484163-7529414344d8?w=300',
      ],
      [
        'Творог с бананом',
        330,
        'Б 29 г · Ж 9 г · У 38 г',
        'https://images.unsplash.com/photo-1488477181946-6428a0291777?w=300',
      ],
      [
        'Тост с авокадо',
        410,
        'Б 14 г · Ж 19 г · У 46 г',
        'https://images.unsplash.com/photo-1541519227354-08fa5d50c44d?w=300',
      ],
    ],
    lunch: [
      [
        'Индейка с киноа',
        510,
        'Б 42 г · Ж 15 г · У 47 г',
        'https://images.unsplash.com/photo-1547592180-85f173990554?w=300',
      ],
      [
        'Паста с тунцом',
        560,
        'Б 36 г · Ж 16 г · У 62 г',
        'https://images.unsplash.com/photo-1473093295043-cdd812d0e601?w=300',
      ],
      [
        'Тофу с овощами',
        420,
        'Б 29 г · Ж 17 г · У 39 г',
        'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=300',
      ],
    ],
    dinner: [
      [
        'Треска с овощами',
        390,
        'Б 38 г · Ж 12 г · У 27 г',
        'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?w=300',
      ],
      [
        'Куриный боул',
        470,
        'Б 40 г · Ж 13 г · У 45 г',
        'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=300',
      ],
      [
        'Овощной суп',
        310,
        'Б 16 г · Ж 9 г · У 39 г',
        'https://images.unsplash.com/photo-1547592166-23ac45744acd?w=300',
      ],
    ],
    snack: [
      [
        'Протеиновый смузи',
        240,
        'Б 24 г · Ж 5 г · У 25 г',
        'https://images.unsplash.com/photo-1553530666-ba11a7da3888?w=300',
      ],
      [
        'Яблоко и йогурт',
        190,
        'Б 14 г · Ж 4 г · У 27 г',
        'https://images.unsplash.com/photo-1488477181946-6428a0291777?w=300',
      ],
    ],
  },
  metricInfo: {
    weight: [
      'Вес',
      '74.2 кг',
      'Целевой диапазон 72--76 кг. Динамика стабильная.',
      'В норме',
      'good',
    ],
    pulse: [
      'Пульс',
      '72 bpm',
      'Спокойный пульс соответствует текущему восстановлению.',
      'Норма',
      'good',
    ],
    sleep: [
      'Сон',
      '7.2 часа',
      'Для полной регенерации желательно 7.5--8 часов.',
      'Хорошо',
      'good',
    ],
    oxygen: [
      'Кислород',
      '98%',
      'Показатель находится в нормальном диапазоне.',
      'Норма',
      'good',
    ],
    hrv: [
      'ВСР',
      '64 мс',
      'Хорошая вариабельность сердечного ритма.',
      'Хорошо',
      'good',
    ],
    stress: [
      'Стресс',
      '32',
      'Уровень умеренный. Помогут дыхание и прогулка.',
      'Умеренный',
      'low',
    ],
    fat: [
      'Жир',
      '18.4%',
      'Показатель отмечен как ниже нормы в демо-данных.',
      'Ниже нормы',
      'low',
    ],
    muscle: [
      'Мышцы',
      '34.8 кг',
      'Показатель отмечен как выше нормы в демо-данных.',
      'Выше нормы',
      'high',
    ],
    protein: [
      'Белок',
      '16.2%',
      'Показатель находится в целевом диапазоне демо-данных.',
      'Норма',
      'good',
    ],
    bmi: [
      'ИМТ',
      '23.4',
      'Индекс массы тела в пределах нормы.',
      'Норма',
      'good',
    ],
  },
  achievements: [
    {
      name: '7 дней движения',
      done: true,
      icon: 'fa-fire',
      desc: 'Выполняй тренировки 7 дней подряд.',
    },
    {
      name: 'Белковый марафон',
      done: true,
      icon: 'fa-dumbbell',
      desc: 'Набирай 120+ г белка 5 дней.',
    },
    {
      name: 'Ранняя пташка',
      done: false,
      icon: 'fa-sun',
      desc: 'Просыпайся до 7:00 3 дня.',
    },
    {
      name: '10 000 шагов',
      done: false,
      icon: 'fa-shoe-prints',
      desc: 'Проходи 10 000 шагов в день.',
    },
    {
      name: 'Водный баланс',
      done: true,
      icon: 'fa-droplet',
      desc: 'Пей 2 литра воды 7 дней подряд.',
    },
    {
      name: 'Золотой ритм',
      done: false,
      icon: 'fa-trophy',
      desc: 'Достигни уровня 10.',
    },
    {
      name: 'Марафонец',
      done: false,
      icon: 'fa-medal',
      desc: '30 тренировок за месяц.',
    },
  ],
  activeDays: 12,
  survey: {
    step: 0,
    allergies: [],
    restrictions: [],
    goals: [],
    diet: '',
    activity: '',
    sleepHours: '',
    waterIntake: '',
    trainingDays: '',
    preferredWorkouts: [],
  },
  registered: false,
  guest: false,
  region: 'RU',
  surveyCompleted: false,
  surveyDeferred: false,
  chatConsent: false,
  chatSettings: {
    allowGuest: false,
    privateMessages: true,
    onlineStatus: false,
    readReceipts: true,
    notifications: true,
  },
  registrationData: { email: '', password: '', confirm: '', code: '' },
  chatContacts: [
    {
      name: 'Анна',
      last: 'Отлично! Завтра в 18:30?',
      time: '12:30',
      unread: 2,
      avatar: 'https://i.pravatar.cc/150?img=1',
      online: true,
      status: 'gym',
    },
    {
      name: 'Дмитрий',
      last: 'Сделал разминку, готов!',
      time: '10:15',
      unread: 0,
      avatar: 'https://i.pravatar.cc/150?img=2',
      online: true,
      status: 'pool',
    },
    {
      name: 'Елена',
      last: 'Спасибо за совет!',
      time: 'Вчера',
      unread: 1,
      avatar: 'https://i.pravatar.cc/150?img=3',
      online: false,
      status: 'offline',
    },
    {
      name: 'Сергей',
      last: 'Когда следующая тренировка?',
      time: 'Вчера',
      unread: 0,
      avatar: 'https://i.pravatar.cc/150?img=4',
      online: true,
      status: 'dnd',
    },
    {
      name: 'Ольга',
      last: 'Отличный результат!',
      time: '2 дня',
      unread: 0,
      avatar: 'https://i.pravatar.cc/150?img=5',
      online: false,
      status: 'offline',
    },
  ],
  chatMessages: [
    {
      from: 'Анна',
      text: 'Привет! Как прошла тренировка?',
      time: '12:20',
      sent: false,
    },
    {
      from: 'Я',
      text: 'Отлично! Сегодня силовая база.',
      time: '12:22',
      sent: true,
    },
    {
      from: 'Анна',
      text: 'Отлично! Завтра в 18:30?',
      time: '12:30',
      sent: false,
    },
  ],
  selectedChat: null,
  selectedCalendarDay: null,
  calendarEvents: {},
  customExercises: [],
  customMeals: [],
  trainingVideos: [
    {
      id: 1,
      title: 'Сильное тело за 20 минут',
      level: 'Средний',
      duration: '20 мин',
      equipment: ['Коврик', 'Гантели 2×5 кг'],
      description:
        'Комплекс без прыжков: приседания, отжимания, выпады, планка. Подходит для дома.',
      image:
        'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=1000',
      type: 'home',
    },
    {
      id: 2,
      title: 'Мобильность после офиса',
      level: 'Лёгкий',
      duration: '15 мин',
      equipment: ['Коврик', 'Резинка'],
      description:
        'Упражнения для спины, таза и дыхания. Снимает напряжение после сидячей работы.',
      image: 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=1000',
      type: 'home',
    },
    {
      id: 3,
      title: 'Техника плавания',
      level: 'Средний',
      duration: '35 мин',
      equipment: ['Очки', 'Шапочка', 'Доска для плавания'],
      description:
        'Разминка в воде, свободный стиль, спокойное плавание. Для бассейна.',
      image:
        'https://images.unsplash.com/photo-1530549387789-4c1017266635?w=1000',
      type: 'pool',
    },
    {
      id: 4,
      title: 'Кардио-интервалы',
      level: 'Высокий',
      duration: '25 мин',
      equipment: ['Коврик', 'Скакалка'],
      description: 'Интенсивные интервальные тренировки для сжигания жира.',
      image:
        'https://images.unsplash.com/photo-1518611012118-696072aa579a?w=1000',
      type: 'home',
    },
    {
      id: 5,
      title: 'Йога для начинающих',
      level: 'Лёгкий',
      duration: '30 мин',
      equipment: ['Коврик'],
      description: 'Мягкая йога для гибкости и расслабления.',
      image: 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=1000',
      type: 'home',
    },
  ],
  progressGoals: {
    week: {
      label: 'Неделя',
      options: [
        { label: '3 дня', days: 3 },
        { label: '5 дней', days: 5 },
      ],
      selected: 0,
    },
    month: {
      label: 'Месяц',
      options: [
        { label: '10 дней', days: 10 },
        { label: '20 дней', days: 20 },
        { label: '30 дней', days: 30 },
      ],
      selected: 0,
    },
    year: {
      label: 'Год',
      options: [
        { label: '3 месяца', days: 90 },
        { label: '6 месяцев', days: 180 },
        { label: '9 месяцев', days: 270 },
        { label: '12 месяцев', days: 365 },
      ],
      selected: 0,
    },
  },
  currentProgressView: 'week',
  showDateModal: false,
  dateModalDate: null,
  selectedAchievement: null,
  selectedStory: null,
  storySeen: {},
  storyPaused: false,
  waterIntake: 0,
  waterDate: '',
  waterGoal: 8,
  completedWorkouts: [],
  dailyCompleted: 0,
  xp: 0,
  trainingMinutes: 0,
  caloriesBurned: 0,
  lastWaterUpdate: Date.now(),
  biometrics: [],
  bodyComposition: [],
  trainingPlans: [],
  selectedPlanId: null,
  mealsList: [],
  calendarEventsList: [],
  achievementsBackend: [],
  videos: [],
  conditions: [],
  menstrualCycles: [],
  profileLoaded: false,
  aiClassification: null,
  aiPlan: null,
  aiDiet: null,
  loading: {},
  lifeHacks: [
    {
      icon: 'fa-lightbulb',
      title: 'Пей воду до еды',
      text: 'Стакан воды за 20 минут до приёма пищи помогает контролировать аппетит и улучшает пищеварение.',
    },
    {
      icon: 'fa-clock',
      title: 'Правильный завтрак',
      text: 'Завтракай в течение часа после пробуждения --- это запускает метаболизм и даёт энергию на день.',
    },
    {
      icon: 'fa-bed',
      title: 'Сон и восстановление',
      text: 'Ложись спать до 23:00 --- гормон роста вырабатывается с 22:00 до 2:00, что важно для восстановления мышц.',
    },
    {
      icon: 'fa-utensils',
      title: 'Белок после тренировки',
      text: 'Употреби 20--30 г белка в течение 30 минут после тренировки для оптимального восстановления мышц.',
    },
    {
      icon: 'fa-heart',
      title: 'Сердечный ритм',
      text: 'Следи за пульсом во время тренировки. Оптимальная зона --- 60-80% от максимального.',
    },
    {
      icon: 'fa-moon',
      title: 'Режим сна',
      text: 'Стабильное время отхода ко сну улучшает качество восстановления.',
    },
  ],
  onlineUsers: 8,
  points: 1270,
  level: 5,
  streak: 12,
  maxStreak: 18,
  xpToNextLevel: 300,
  dailyQuests: [
    { name: 'Выпить 8 стаканов воды', done: false, xp: 20 },
    { name: 'Пройти 10 000 шагов', done: false, xp: 30 },
    { name: 'Выполнить тренировку', done: false, xp: 40 },
  ],
  instructions: {
    gym: '1. Разминка 5-10 мин (кардио + суставная гимнастика).\n2. Силовая тренировка: 3-4 подхода по 8-12 повторений на каждую группу мышц.\n3. Заминка: растяжка 5-10 мин.\n4. Пей воду во время тренировки (по глотку каждые 15 мин).\n5. Используй правильную технику, не гонись за весом.',
    pool: '1. Разминка на суше: 5 мин (махи, наклоны).\n2. В воде: 5 мин спокойного плавания для разогрева.\n3. Основная часть: интервалы (например, 4×50 м кроль с отдыхом 30 сек).\n4. Заминка: 5 мин спокойного плавания брассом.\n5. После бассейна: душ и растяжка.',
    hygiene:
      '1. Всегда принимай душ до и после тренировки.\n2. Используй индивидуальное полотенце и тапочки в бассейне.\n3. Дезинфицируй инвентарь после использования.\n4. Следи за чистотой спортивной одежды.\n5. Не занимайся при плохом самочувствии.',
  },
  friends: [
    {
      name: 'Анна',
      image: 'https://i.pravatar.cc/150?img=1',
      online: true,
      status: 'gym',
      bio: 'Бегу к своим целям маленькими шагами каждый день.',
      achievements: 8,
      workouts: 34,
      added: true,
    },
    {
      name: 'Дмитрий',
      image: 'https://i.pravatar.cc/150?img=2',
      online: true,
      status: 'pool',
      bio: 'Сила, дисциплина и хороший сон.',
      achievements: 12,
      workouts: 48,
      added: false,
    },
    {
      name: 'Елена',
      image: 'https://i.pravatar.cc/150?img=3',
      online: false,
      status: 'offline',
      bio: 'Йога и забота о себе в своём ритме.',
      achievements: 15,
      workouts: 61,
      added: false,
    },
    {
      name: 'Сергей',
      image: 'https://i.pravatar.cc/150?img=4',
      online: true,
      status: 'dnd',
      bio: 'Работаю над выносливостью и результатом.',
      achievements: 6,
      workouts: 27,
      added: false,
    },
    {
      name: 'Ольга',
      image: 'https://i.pravatar.cc/150?img=5',
      online: false,
      status: 'offline',
      bio: 'Здоровье --- это ежедневный выбор.',
      achievements: 10,
      workouts: 39,
      added: false,
    },
    {
      name: 'Алексей',
      image: 'https://i.pravatar.cc/150?img=6',
      online: true,
      status: 'gym',
      bio: 'Каждая тренировка --- это маленькая победа.',
      achievements: 5,
      workouts: 22,
      added: false,
    },
  ],
  stickers: [
    '💪',
    '🔥',
    '👏',
    '🏆',
    '❤️',
    '🥳',
    '💧',
    '🏋️',
    '🚀',
    '⭐',
    '🌈',
    '🎯',
  ],
  pinnedPlaces: [
    { name: 'Дом', icon: 'fa-house', color: '#6fae20', x: 20, y: 28 },
    { name: 'Зал', icon: 'fa-dumbbell', color: '#19d8da', x: 62, y: 62 },
    {
      name: 'Бассейн',
      icon: 'fa-person-swimming',
      color: '#19d8da',
      x: 78,
      y: 26,
    },
    { name: 'Работа', icon: 'fa-building', color: '#a78bfa', x: 42, y: 42 },
    {
      name: 'Учёба',
      icon: 'fa-graduation-cap',
      color: '#f5d45d',
      x: 82,
      y: 72,
    },
  ],
  hackIndex: 0,
  hackList: [
    [
      'fa-droplet',
      'Пей воду до еды',
      'Стакан воды за 20 минут до еды помогает поддерживать водный баланс.',
    ],
    [
      'fa-bed',
      'Сон --- часть прогресса',
      'Стабильный сон 7--9 часов помогает восстановлению мышц.',
    ],
    [
      'fa-person-running',
      'Не пропускай разминку',
      '5--10 минут разминки подготавливают суставы и мышцы к нагрузке.',
    ],
    [
      'fa-dumbbell',
      'Белок после тренировки',
      'Добавь источник белка в течение двух часов после занятия.',
    ],
    [
      'fa-heart',
      'Следи за пульсом',
      'Оптимальная зона пульса для жиросжигания --- 60-70% от максимального.',
    ],
    [
      'fa-moon',
      'Режим сна',
      'Стабильный график сна улучшает восстановление и продуктивность.',
    ],
  ],
  stories: [
    {
      title: 'Сила без перегруза',
      description: 'Тренировки под состояние',
      text: 'Слушай своё тело и выбирай нагрузку, которая приносит пользу.',
      image:
        'https://images.unsplash.com/photo-1517836357463-d25dfeac3438?w=900',
    },
    {
      title: 'Питание в ритме',
      description: 'КБЖУ без сложностей',
      text: 'Баланс питания помогает сохранять энергию и поддерживать результат.',
      image:
        'https://images.unsplash.com/photo-1490645935967-10de6ba17061?w=900',
    },
    {
      title: 'Улыбайся и двигайся',
      description: 'Энергия каждый день',
      text: 'Регулярное движение помогает укреплять тело и улучшать настроение.',
      image: 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=900',
    },
    {
      title: 'Новая привычка',
      description: '12 дней серии',
      text: 'Каждый активный день приближает тебя к цели.',
      image:
        'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=900',
    },
    {
      title: 'Сила духа',
      description: 'Ментальный фитнес',
      text: 'Крепкий дух помогает преодолевать любые физические барьеры.',
      image:
        'https://images.unsplash.com/photo-1518611012118-696072aa579a?w=900',
    },
    {
      title: 'Гармония тела',
      description: 'Баланс и гибкость',
      text: 'Сочетание силы и гибкости создаёт идеальный баланс для здоровья.',
      image: 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=900',
    },
    {
      title: 'Водная стихия',
      description: 'Плавание и здоровье',
      text: 'Плавание укрепляет все группы мышц и улучшает дыхательную систему.',
      image:
        'https://images.unsplash.com/photo-1530549387789-4c1017266635?w=900',
    },
    {
      title: 'Утренний ритуал',
      description: 'Заряд энергии',
      text: 'Утренняя зарядка запускает обмен веществ и даёт энергию на весь день.',
      image:
        'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=900',
    },
  ],
  nutritionData: {
    day: {
      labelRu: 'Сегодня',
      labelEn: 'Today',
      calories: 1680,
      goal: 2350,
      protein: 128,
      fats: 56,
      carbs: 185,
    },
    week: {
      labelRu: 'Неделя',
      labelEn: 'Week',
      calories: 11760,
      goal: 16450,
      protein: 896,
      fats: 392,
      carbs: 1295,
    },
    month: {
      labelRu: 'Месяц',
      labelEn: 'Month',
      calories: 50400,
      goal: 70500,
      protein: 3840,
      fats: 1680,
      carbs: 5550,
    },
  },
  trainingData: {
    day: {
      labelRu: 'День',
      labelEn: 'Day',
      completed: 2,
      goal: 3,
      calories: 420,
      minutes: 42,
      workouts: ['Силовая база', 'Разминка', 'Растяжка'],
    },
    week: {
      labelRu: 'Неделя',
      labelEn: 'Week',
      completed: 4,
      goal: 5,
      calories: 2140,
      minutes: 168,
      workouts: [
        'Силовая база',
        'Бассейн',
        'Мобильность',
        'Кардио',
        'Восстановление',
      ],
    },
    month: {
      labelRu: 'Месяц',
      labelEn: 'Month',
      completed: 16,
      goal: 20,
      calories: 12480,
      minutes: 720,
      workouts: [
        'Силовые тренировки',
        'Плавание',
        'Кардио',
        'Мобильность',
        'Восстановление',
      ],
    },
  },
  nutritionPeriod: 'day',
  trainingPeriod: 'day',
  videoIndex: 0,
  resetStep: 0,
  resetEmail: '',
  legalReturnScreen: null,
  __toast: null,
  __toastTimer: null,
};

export function getInitialState() {
  try {
    const saved = loadState() || {};
    return {
      ...defaultState,
      screen: saved.screen || 'login',
      theme: saved.theme || 'dark',
      highContrast: saved.highContrast || false,
      language: saved.language || 'ru',
      calendarMonthIndex:
        saved.calendarMonthIndex !== undefined
          ? saved.calendarMonthIndex
          : new Date().getMonth(),
      calendarYear: saved.calendarYear || new Date().getFullYear(),
      profileImage: saved.profileImage || '',
      profile: {
        ...defaultState.profile,
        name: saved.profileName || defaultState.profile.name,
        gender: saved.gender || defaultState.profile.gender,
        email: saved.email || defaultState.profile.email,
        phone: saved.phone || defaultState.profile.phone,
        twoFactor: saved.twoFactor || defaultState.profile.twoFactor,
        backupCodesRemaining: saved.backupCodesRemaining || 0,
        devices: saved.devices || defaultState.profile.devices,
        bio: saved.bio || defaultState.profile.bio,
        status: saved.status || defaultState.profile.status,
        friends:
          saved.friendsCount !== undefined
            ? saved.friendsCount
            : defaultState.profile.friends,
      },
      calendarEvents: saved.calendarEvents || {},
      customExercises: saved.customExercises || [],
      customMeals: saved.customMeals || [],
      waterIntake: saved.waterIntake || 0,
      waterDate: saved.waterDate || '',
      points: saved.points || 1270,
      level: saved.level || 5,
      streak: saved.streak || 12,
      maxStreak: saved.maxStreak || 18,
      friends: saved.friends || defaultState.friends,
      pinnedPlaces: saved.pinnedPlaces || defaultState.pinnedPlaces,
      hackIndex: saved.hackIndex || 0,
      nutritionPeriod: saved.nutritionPeriod || 'day',
      trainingPeriod: saved.trainingPeriod || 'day',
      completedWorkouts: saved.completedWorkouts || [],
      dailyCompleted: saved.dailyCompleted || 0,
      xp: saved.xp || 0,
      trainingMinutes: saved.trainingMinutes || 0,
      caloriesBurned: saved.caloriesBurned || 0,
      biometrics: saved.biometrics || [],
      bodyComposition: saved.bodyComposition || [],
      trainingPlans: saved.trainingPlans || [],
      selectedPlanId: saved.selectedPlanId || null,
      mealsList: saved.mealsList || [],
      calendarEventsList: saved.calendarEventsList || [],
      achievementsBackend: saved.achievementsBackend || [],
      videos: saved.videos || [],
      conditions: saved.conditions || [],
      menstrualCycles: saved.menstrualCycles || [],
      profileLoaded: false,
      aiClassification: saved.aiClassification || null,
      aiPlan: saved.aiPlan || null,
      aiDiet: saved.aiDiet || null,
      loading: saved.loading || {},
      survey: saved.survey || defaultState.survey,
      surveyCompleted: saved.surveyCompleted || false,
      surveyDeferred: saved.surveyDeferred || false,
      registered: saved.registered || false,
      guest: saved.guest || false,
      region: saved.region || 'RU',
      chatConsent: saved.chatConsent || false,
      chatSettings: saved.chatSettings || defaultState.chatSettings,
      chatMessages: saved.chatMessages || defaultState.chatMessages,
      storySeen: saved.storySeen || {},
      twoFactorSetup: saved.twoFactorSetup || null,
      twoFactorTempToken: saved.twoFactorTempToken || null,
    };
  } catch {
    return { ...defaultState };
  }
}
