apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
  - rbac.yaml
  - configmap.yaml
  - basic-auth-secret.yaml
namespace: fitness-platform-production
labels:
  - pairs:
      app.kubernetes.io/part-of: monitoring
      zone: tracing-zone
    includeSelectors: true
