apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: user-service-db-credentials
  namespace: fitness-platform-production
  labels:
    app: user-service
spec:
  refreshInterval: 15m
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: user-service-db-credentials
    creationPolicy: Owner
  data:
    - secretKey: POSTGRES_USER
      remoteRef:
        key: database/creds/user-service-role
        property: username
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: database/creds/user-service-role
        property: password
