apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: data-processor-db-credentials
  namespace: fitness-platform-production
  labels:
    app: data-processor
spec:
  refreshInterval: 15m
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: data-processor-db-credentials
    creationPolicy: Owner
  data:
    - secretKey: POSTGRES_USER
      remoteRef:
        key: database/creds/data-processor-role
        property: username
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: database/creds/data-processor-role
        property: password
