apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: vault-backend
  namespace: vault
spec:
  provider:
    vault:
      server: "https://vault.vault:8200"
      path: "database"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "user-service-vault-role"
          serviceAccountRef:
            name: "user-service-vault-sa"
            namespace: "fitness-platform-production"
