apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - prometheus
  - alertmanager
  - grafana
  - fluent-bit
namespace: fitness-platform-production
labels:
  - pairs:
      app.kubernetes.io/part-of: monitoring
      zone: monitoring-zone
    includeSelectors: true
