export const EXERCISE_NAME_MAP = {
  jumping_jacks: 'Прыжки на месте',
  arm_circles: 'Вращение руками',
  high_knees: 'Подъем коленей',
  pushups: 'Отжимания',
  squats: 'Приседания',
  plank: 'Планка',
  lunges: 'Выпады',
  burpees: 'Бёрпи',
  mountain_climbers: 'Альпинист',
  stretching: 'Растяжка',
  deep_breathing: 'Глубокое дыхание',
  treadmill_walk: 'Ходьба на беговой дорожке',
  dynamic_stretch: 'Динамическая растяжка',
  bench_press: 'Жим лёжа',
  deadlift: 'Становая тяга',
  leg_press: 'Жим ногами',
  lat_pulldown: 'Тяга верхнего блока',
  shoulder_press: 'Жим плечами',
  cable_rows: 'Тяга блока',
  foam_rolling: 'Фоам-роллинг',
  static_stretching: 'Статическая растяжка',
  easy_swim: 'Лёгкое плавание',
  freestyle_intervals: 'Интервалы вольным стилем',
  breaststroke: 'Брасс',
  backstroke: 'На спине',
  kickboard_drills: 'Работа с доской',
  pool_stretching: 'Растяжка в бассейне',
  brisk_walk: 'Быстрая ходьба',
  leg_swings: 'Махи ногами',
  running: 'Бег',
  cycling: 'Велосипед',
  hill_sprints: 'Спринты в гору',
  bodyweight_circuit: 'Круговая тренировка',
  walk_recovery: 'Ходьба',
  active_recovery: 'Активное восстановление',
  light_warmup: 'Лёгкая разминка',
  breathing_exercises: 'Дыхательные упражнения',
};
