apiVersion: v1
kind: LimitRange
metadata:
  name: ingress-nginx-limits
  namespace: ingress-nginx
spec:
  limits:
    - type: Container
      default:
        cpu: "100m"
        memory: "128Mi"
      defaultRequest:
        cpu: "50m"
        memory: "64Mi"
      max:
        cpu: "2000m"
        memory: "2Gi"
      min:
        cpu: "10m"
        memory: "16Mi"
