apiVersion: v1
kind: LimitRange
metadata:
  name: pod-limits
  namespace: fitness-platform-production
spec:
  limits:
    - type: Container
      default:
        memory: "64Mi"
        cpu: "50m"
      defaultRequest:
        memory: "32Mi"
        cpu: "25m"
      max:
        memory: "384Mi" # Максимум на один контейнер (чтобы прошли RabbitMQ и ML)
        cpu: "500m"
      min:
        memory: "16Mi"
        cpu: "10m"
    - type: Pod
      max:
        memory: "512Mi" # Максимум на один под
        cpu: "1000m"
