apiVersion: v1
kind: LimitRange
metadata:
  name: pod-limits
  namespace: fitness-platform-production
spec:
  limits:
    - type: Container
      default:
        memory: "64Mi"
        cpu: "50m"
      defaultRequest:
        memory: "32Mi"
        cpu: "25m"
      max:
        memory: "256Mi" # Ни один контейнер не возьмёт больше 256MB
        cpu: "200m"
      min:
        memory: "16Mi"
        cpu: "10m"
    - type: Pod
      max:
        memory: "512Mi" # Ни один под не займёт больше 512MB суммарно
        cpu: "400m"
