helperPod.yaml: |
  apiVersion: v1
  kind: Pod
  metadata:
    name: helper-pod
  spec:
    priorityClassName: system-node-critical
    tolerations:
      - key: node.kubernetes.io/disk-pressure
        operator: Exists
        effect: NoSchedule
    containers:
      - name: helper-pod
        image: busybox
        imagePullPolicy: IfNotPresent
        command:
          - "sh"
          - "-c"
          - "mkdir -m 0777 -p \"$VOL_DIR\" && sleep 3600"