apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-quota
  namespace: fitness-platform-production
spec:
  hard:
    requests.cpu: "1000m"
    requests.memory: 1000Mi
    limits.cpu: "2000m"
    limits.memory: 1900Mi # Увеличено с 1600Mi, чтобы хватило на seed-admin/migrate-db (по 96Mi)
    pods: "110"
    persistentvolumeclaims: "5"
