apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-quota
  namespace: fitness-platform-production
spec:
  hard:
    requests.cpu: "900m"
    requests.memory: 1000Mi
    limits.cpu: "1400m"
    limits.memory: 1800Mi
    pods: "30"
    persistentvolumeclaims: "5"
