apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-quota
  namespace: fitness-platform-production
spec:
  hard:
    requests.cpu: "2"
    requests.memory: 1Gi
    limits.cpu: "4"
    limits.memory: 2Gi
    pods: "30"
    services: "20"
    persistentvolumeclaims: "10"
