apiVersion: v1
kind: ServiceAccount
metadata:
  name: app-service-account
  labels:
    app: fitness-platform
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: gateway-sa
  labels:
    app: fitness-platform
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: user-service-sa
  labels:
    app: fitness-platform
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: biometric-service-sa
  labels:
    app: fitness-platform
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: training-service-sa
  labels:
    app: fitness-platform
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: device-connector-sa
  labels:
    app: fitness-platform
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: classifier-sa
  labels:
    app: fitness-platform
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ml-generator-sa
  labels:
    app: fitness-platform
automountServiceAccountToken: false
