apiVersion: v1
kind: ServiceAccount
metadata:
  name: open-wearables-sa
  namespace: fitness-platform-production
  labels:
    app: open-wearables
    app.kubernetes.io/name: open-wearables
    app.kubernetes.io/part-of: fitness-platform
automountServiceAccountToken: false
