apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - gateway-vpa.yaml
  - user-service-vpa.yaml
  - biometric-service-vpa.yaml
  - training-service-vpa.yaml
  - classifier-vpa.yaml
