apiVersion: v1
kind: Service
metadata:
  name: logstash
  labels:
    app: logstash
spec:
  type: ClusterIP
  selector:
    app: logstash
  ports:
    - name: tcp
      port: 5044
      targetPort: 5044
    - name: beats
      port: 5045
      targetPort: 5045
    - name: api
      port: 9600
      targetPort: 9600