SecRuleEngine On

SecRequestBodyAccess On
SecRequestBodyNoFilesLimit 131072
SecRequestBodyInMemoryLimit 131072
SecRequestBodyLimit Action
SecResponseBodyAccess Off

SecDebugLog /var/log/modsec/debug.log
SecDebugLogLevel 3
SecAuditEngine RelevantOnly
SecAuditLogRelevantStatus "^(?:5|4(?!04))"
SecAuditLogParts ABIJDEFHZ
SecAuditLogType Serial
SecAuditLog /var/log/modsec/audit.log
SecArgumentSeparator &
SecArgumentSeparator " "
SecUploadKeepFiles Off
SecTmpDir /tmp/modsecurity
SecDataDir /tmp/modsecurity/data

Include /etc/nginx/modsecurity/crs-setup.conf
Include /etc/nginx/modsecurity/rules/*.conf
