apiVersion: v1
kind: LimitRange
metadata:
  name: local-path-storage-limits
  namespace: local-path-storage
spec:
  limits:
  - type: Container
    default:
      cpu: "50m"
      memory: "64Mi"
    defaultRequest:
      cpu: "10m"
      memory: "16Mi"
    max:
      cpu: "500m"
      memory: "512Mi"
    min:
      cpu: "5m"
      memory: "8Mi"
