apiVersion: v1
kind: Service
metadata:
  name: data-processor
  namespace: fitness-platform-production
  labels:
    app: data-processor
    tier: backend
    app.kubernetes.io/name: data-processor
    app.kubernetes.io/instance: data-processor
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: fitness-platform
spec:
  selector:
    app: data-processor
  ports:
    - port: 8084
      targetPort: 8084
      name: http
    - port: 9092
      targetPort: 9092
      name: metrics
  type: ClusterIP
