apiVersion: v1
kind: Service
metadata:
  name: device-aggregator
  namespace: fitness-platform-production
  labels:
    app: device-aggregator
    tier: backend
    app.kubernetes.io/name: device-aggregator
    app.kubernetes.io/instance: device-aggregator
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: fitness-platform
spec:
  selector:
    app: device-aggregator
  ports:
    - port: 8083
      targetPort: 8083
      name: http
    - port: 9093
      targetPort: 9093
      name: metrics
  type: ClusterIP
