apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - postgres-service.yaml
  - redis-service.yaml
  - rabbitmq-service.yaml
  - user-service.yaml
  - biometric-service.yaml
  - training-service.yaml
  - gateway-service.yaml
  - device-connector-service.yaml
  - classifier-service.yaml
  - ml-generator-service.yaml
